"""Remove target_language from User model

Revision ID: 0ee17429ec06
Revises: e4c0a491aee9
Create Date: 2025-03-16 00:14:05.363210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ee17429ec06'
down_revision = 'e4c0a491aee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('wallet_address',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=42),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('wallet_address',
               existing_type=sa.String(length=42),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###
