"""Add wallet_address to User model

Revision ID: e4c0a491aee9
Revises: 
Create Date: 2025-03-14 17:35:51.380492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c0a491aee9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_address', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_user_wallet_address', ['wallet_address'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_wallet_address', type_='unique')
        batch_op.drop_column('wallet_address')

    # ### end Alembic commands ###
